export { Hero } from './Hero'
export { Navbar } from './Navbar'
export { Info } from './Info'
export { Collections } from './Collections/Collections'
export { CarrouselProducts } from './CarrouselProducts/CarrouselProducts'
export { Follow} from './Follow/Follow'
export { Footer } from './Footer/Footer'